name: mobile_developer_interview_mastery
description: A comprehensive, production-ready interview preparation workspace in Dart & Flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.5.1
  provider: ^6.1.1
  equatable: ^2.0.5
  async: ^2.11.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  bloc_test: ^9.1.5
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/00_flutter_ui_playground/assets/images/1.png
    - lib/00_flutter_ui_playground/assets/images/2.png
    - lib/00_flutter_ui_playground/assets/images/3.png
    - lib/00_flutter_ui_playground/assets/images/4.png
    - lib/00_flutter_ui_playground/assets/images/5.png
    - lib/00_flutter_ui_playground/assets/images/6.png
    - lib/00_flutter_ui_playground/assets/images/7.png
    - lib/00_flutter_ui_playground/assets/images/8.png
    - lib/00_flutter_ui_playground/assets/images/9.png
    - lib/00_flutter_ui_playground/assets/images/10.png
